version: '3'
services:
  db:
    image: 'postgres:13.7'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    ports:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
 
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
     - .:/jenkact-docker-atm
    ports:
      - "3000:3000"
    depends_on:
      - db

  redis:
    image: redis
    ports:
      - "6379"
volumes:
  db_data:
