version: '3'
services:
  db:
    image: 'postgres:13.7'
    ports:
      - "5432"
 
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/jenkact
    ports:
      - "3000:3000"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=
    depends_on:
      - db

  redis:
    image: redis
    ports:
      - "6379"
