version: '3'
services:
  db:
    image: 'postgres:13.7'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432"
 
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/jenkact
    ports:
      - "3000:3000"
    depends_on:
      - db

  redis:
    image: redis
    ports:
      - "6379"
      
volumes:
  db_data:
