db:
  image: postgres
  ports:
    - "5432"
  volumes:
      - db_data:/var/lib/postgresql/data
 
redis:
  image: redis
  ports:
    - "6379"
 
web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/jenkact
  ports:
    - "3000:3000"
  environment:
    - DB_USERNAME=postgres
    - DB_PASSWORD=
  links:
    - db
    
volumes:
    db_data:
