default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: pass
  password: pass

development:
  <<: *default
  database: jenkact_development

test:
  <<: *default
  database: jenkact_test

production:
  <<: *default
  database: jenkact_production
